name: 'Get Conan'
description: 'Installs Conan'
author: 'TurtleBrowser'

inputs:
  version:
    description: "Wanted Conan version"
    required: false
    default: ''

outputs:
  version:
    description: "The version of Conan which was installed"
    value: ${{ steps.output_version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Create virtualenv on macOS
      if: ${{ runner.os == 'macOS' }}
      run: |
        python3 -m venv .
        source ./bin/activate
      shell: bash

    - name: Install Python setuptools
      run: python3 -m pip install wheel setuptools
      shell: bash

    - name: Install Conan latest
      if: ${{ inputs.version == '' }}
      run: python3 -m pip install conan --upgrade
      shell: bash

    - name: Install Conan version ${{ inputs.version }}
      if: ${{ inputs.version != '' }}
      run: python3 -m pip install conan==${{ inputs.version }} --upgrade
      shell: bash

    - name: Fix path on Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Fill in output variable
      id: output_version
      shell: bash
      run: |
        conan --version
        echo "version=$(conan --version)" >> $GITHUB_OUTPUT

branding:
  icon: "archive"
  color: "green"
